max_width = 120
tab_spaces = 4
fn_single_line = false
match_block_trailing_comma = true
normalize_comments = true
wrap_comments = true
imports_granularity = "Module"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
normalize_doc_attributes = true
edition = "2021"
