package coemu:msg-connect@0.1.0;

world msg-connect {
		use coemu:actor/types@0.1.0.{actor-handle, packet};
		variant error {
				decode(string),
				shutdown,
		}
		export process: func(packet: packet, actor: borrow<actor-handle>) -> result<_, error>;
}

// vim: set ft=typescript ts=2 sw=4 noet:
