CREATE TABLE IF NOT EXISTS npcs (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  kind INTEGER NOT NULL,
  look INTEGER NOT NULL,
  map_id INTEGER NOT NULL CONSTRAINT fk_npc_map REFERENCES maps(id) ON DELETE CASCADE,
  x INTEGER NOT NULL CHECK(x >= 0),
  y INTEGER NOT NULL CHECK(y >= 0),
  base INTEGER NOT NULL,
  sort INTEGER NOT NULL,
  level INTEGER NOT NULL,
  life INTEGER NOT NULL,
  defense INTEGER NOT NULL,
  magic_defense INTEGER NOT NULL
);
