-- Add migration script here
CREATE TABLE IF NOT EXISTS characters (
    character_id INTEGER PRIMARY KEY,
    account_id INTEGER NOT NULL CONSTRAINT fk_account REFERENCES accounts(account_id) ON DELETE CASCADE,
    realm_id INTEGER NOT NULL CONSTRAINT fk_realm REFERENCES realms(realm_id),
    name TEXT UNIQUE NOT NULL CHECK (length(name) <= 32),
    mesh INTEGER NOT NULL DEFAULT 1003,
    avatar INTEGER NOT NULL DEFAULT 1,
    hair_style INTEGER NOT NULL DEFAULT 535,
    silver INTEGER NOT NULL DEFAULT 1000 CHECK (silver >= 0),
    cps INTEGER NOT NULL DEFAULT 0 CHECK (cps >= 0),
    current_class INTEGER NOT NULL DEFAULT 10 CHECK (current_class > 0),
    previous_class INTEGER NOT NULL DEFAULT 0 CHECK (previous_class >= 0),
    rebirths INTEGER NOT NULL DEFAULT 0 CHECK (rebirths >= 0),
    level INTEGER NOT NULL DEFAULT 1 CHECK (level > 0),
    experience INTEGER NOT NULL DEFAULT 0 CHECK (experience >= 0),
    map_id INTEGER NOT NULL DEFAULT 1002,
    x INTEGER NOT NULL DEFAULT 430,
    y INTEGER NOT NULL DEFAULT 380,
    virtue INTEGER NOT NULL DEFAULT 0,
    strength INTEGER NOT NULL DEFAULT 4,
    agility INTEGER NOT NULL DEFAULT 6,
    vitality INTEGER NOT NULL DEFAULT 12,
    spirit INTEGER NOT NULL DEFAULT 0,
    attribute_points INTEGER NOT NULL DEFAULT 0 CHECK (attribute_points >= 0),
    health_points INTEGER NOT NULL DEFAULT 12 CHECK (health_points >= 0),
    mana_points INTEGER NOT NULL DEFAULT 0 CHECK (mana_points >= 0),
    kill_points INTEGER NOT NULL DEFAULT 0 CHECK (kill_points >= 0)
);
