-- Add migration script here
CREATE TABLE IF NOT EXISTS characters (
    character_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    account_id INT NOT NULL CONSTRAINT fk_account REFERENCES accounts(account_id) ON DELETE CASCADE,
    realm_id INT NOT NULL CONSTRAINT fk_realm REFERENCES realms(realm_id),
    name VARCHAR(15) UNIQUE NOT NULL,
    mesh INT NOT NULL DEFAULT 1003,
    avatar SMALLINT NOT NULL DEFAULT 1,
    hair_style SMALLINT NOT NULL DEFAULT 535,
    silver BIGINT NOT NULL DEFAULT 1000 CHECK ( silver >= 0 ),
    cps BIGINT NOT NULL DEFAULT 0 CHECK ( cps >= 0 ),
    current_class SMALLINT NOT NULL DEFAULT 10 CHECK ( current_class > 0 ),
    previous_class SMALLINT NOT NULL DEFAULT 0 CHECK ( previous_class >= 0 ),
    rebirths SMALLINT NOT NULL DEFAULT 0 CHECK ( rebirths >= 0 ),
    level SMALLINT NOT NULL DEFAULT 1 CHECK ( level > 0 ),
    experience BIGINT NOT NULL DEFAULT 0 CHECK ( experience >= 0 ),
    map_id INT NOT NULL DEFAULT 1002,
    x SMALLINT NOT NULL DEFAULT 430,
    y SMALLINT NOT NULL DEFAULT 380,
    virtue SMALLINT NOT NULL DEFAULT 0,
    strength SMALLINT NOT NULL DEFAULT 4,
    agility SMALLINT NOT NULL DEFAULT 6,
    vitality SMALLINT NOT NULL DEFAULT 12,
    spirit SMALLINT NOT NULL DEFAULT 0,
    attribute_points SMALLINT NOT NULL DEFAULT 0 CHECK ( attribute_points >= 0 ),
    health_points SMALLINT NOT NULL DEFAULT 12 CHECK ( health_points >= 0 ),
    mana_points SMALLINT NOT NULL DEFAULT 0 CHECK ( mana_points >= 0 ),
    kill_points SMALLINT NOT NULL DEFAULT 0 CHECK ( kill_points >= 0 ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
