CREATE TABLE IF NOT EXISTS portals (
    id INTEGER PRIMARY KEY,
    from_map_id INTEGER NOT NULL CONSTRAINT fk_map_from REFERENCES maps(id) ON DELETE CASCADE,
    from_x INTEGER NOT NULL,
    from_y INTEGER NOT NULL,
    to_map_id INTEGER NOT NULL CONSTRAINT fk_map_to REFERENCES maps(id) ON DELETE CASCADE,
    to_x INTEGER NOT NULL,
    to_y INTEGER NOT NULL
);
