[package]
name = "msg-connect"
version = "0.1.0"
edition.workspace = true

[dependencies]
tq-serde.workspace = true
tq-network.workspace = true
tq-system.workspace = true

serde.workspace = true

[features]
default = ["std"]
std = ["tq-serde/std", "tq-network/std", "tq-system/std"]
