[package]
name = "tq-crypto"
version = "0.1.0"
authors = ["Shady Khalifa <dev@shadykhalifa.me>"]
edition.workspace = true

[dependencies]
bytes.workspace = true
parking_lot.workspace = true

[features]
default = ["std"]
std = ["bytes/std"]
