on:
  push:
    branches: [master]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]
  workflow_dispatch:

name: Nightly lints

jobs:
  combo:
    name: Clippy + rustfmt
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ubuntu-latest
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          profile: minimal
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust"

      - name: Setup mold Linker
        uses: rui314/setup-mold@v1

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        env:
          SQLX_OFFLINE: true
        run: cargo clippy -- -D warnings
